travis:
  secure:
    BINSTAR_TOKEN: kDXT1SC1Q4OAej2XQ4BWDvfulYcrJLpmlZ815wDxIbFLQC7hwCb+IyASTfM/biJloa+aBf2ZJMAm1Z8aTHGjfkepuR7x8ANlU2EYCpKBZITJtAbc7aZL86psXu7g2RWdcKGMOYhcbiCVPIuukyG8EvPNtCWBfBO7k/8ETgso3/NNZ9DxTzAic5pzvG1nozImV9UL5hkDN3uGVKo1D2H6Cs9JXs64sr7l963sz2bctnIwdW2e1TicVqpGBqnr0MlPYLvCXiSU3DlTa20JogpKqf5ckZzKk6oY5X7dEntDJy5LXEvBjL/DY34hK47gHcwJdSzhMz7gNh0M6LKX5V6/99WmlZa9dKUqBUpLQS29nMQKuk31ymOLnm/GtjQ41bD+fVWH2b+QZmSvv+lYlRy+MdAp3HskfNZSzQQmT35V9aeNmqovdjpiAJeazVSm0SOTyq3TvYk9/JbxKIn8RhFZEknq9CWS/FkvL+NWv4fiyu1BXQ6vPSKb2IEipSog3Ftz/YtGiSRWSqaR/wLThOom5A84a6gAx8K+an7et0T2oU45ajd3XErapl5R77EXnnotBihsA0CRi9Dy9PZL5BbavgHw7H1vnzH5NXqA4DmviZMKWPKWRg+zH84Y7NtnTMk/BBW1GVsXGmFhqKkpx9Pqr0K42rdRi4yeRrw25uiPFAE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
